# Generated by Django 3.1.5 on 2021-01-05 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('repo_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('is_archived', models.BooleanField()),
                ('is_empty', models.BooleanField()),
                ('is_fork', models.BooleanField()),
                ('is_private', models.BooleanField()),
                ('is_owner', models.BooleanField()),
                ('license', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=110)),
                ('owner', models.CharField(max_length=39)),
                ('description', models.TextField(blank=True, default='')),
                ('language_1', models.JSONField(null=True)),
                ('language_2', models.JSONField(null=True)),
                ('language_3', models.JSONField(null=True)),
                ('pr_count', models.IntegerField()),
                ('star_count', models.IntegerField()),
                ('fork_count', models.IntegerField()),
                ('watcher_count', models.IntegerField()),
                ('release_count', models.IntegerField()),
                ('vulnerability_count', models.IntegerField()),
                ('url', models.URLField()),
                ('hidden', models.BooleanField(default=False)),
                ('rappel_created_at', models.DateTimeField(auto_now_add=True)),
                ('rappel_updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Backlog'), (1, 'Active'), (2, 'Work In Progess'), (3, 'Done'), (4, 'Archive')], default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rappel_updated_at'],
            },
        ),
    ]
